### PR TITLE
Create 20191213.md

### PR DESCRIPTION
**Pull request by Frenchhorn005**
Added Minutes from Dec 13th 2019 TSC meeting

Signed-off-by:  Andre de Waal <andre.dewaal@ibm.com>

### CODE REVIEW

**Comment by jmertic** [comment]
@ProcJimi @GoutamChakraborty @anamecheverri - Can you click on the link below to accept the invite to join this repo so you can approve commits?

https://github.com/odpi/OpenDS4All/invitations

**Comment by anamecheverri** [comment]
John, I get an error.

---------------------------------
Ana Maria Echeverri
www.linkedin.com/in/anamariaecheverriangel/

**Comment by ProcJimi** [comment]
Hi, John--

I also receive an error (below) even though I am logged in

Sorry, we couldn't find that repository invitation. It is possible that the
invitation was revoked or that you are not logged into the invited account.

-jh

**Comment by ProcJimi** [comment]
﻿

Hi, John—

I also receive an error (below) even though I am logged in

Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account. 

-jh

**Comment by jmertic** [comment]
Hey @ProcJimi @GoutamChakraborty @anamecheverri - I just tried removing the invite and sending a new one - you should have an email that indicates you were invited. Let me know if it comes through and if it works. If not - can you ping me on Slack and we can do a quick call to figure it out?

**Comment by ProcJimi** [comment]
Hey, John--

I think it worked.

I clicked and it went through. I'm now showing as a member.

--jh

**Comment by jmertic** [comment]
I see that now too @ProcJimi - great to hear!

@anamecheverri @GoutamChakraborty can you try as well?

**Pull request merged**
