### PR TITLE
Initial stab at an INFO.yaml file

### PR DESCRIPTION
**Pull request by jmertic**
@tykeal - please review and let me know if I got it right.

### CODE REVIEW

**Comment by jmertic** [comment]
@Frenchhorn005 - ignore this for now - this is for hooking into our RE tooling to automate things a bit.

**Comment by Aricg** [comment]
Hi @jmertic I have all the pieces in review to enable info file management for github projects.
https://gerrit.linuxfoundation.org/infra/c/ci-management/+/16237
Perhaps you would like odpi to be a guinea-pig for this?
https://docs.releng.linuxfoundation.org/en/latest/committer-management.html

**Comment by jmertic** [comment]
@Aricg We'd be delighted to! Let me know what you need from me to move forward.

**Comment by jmertic** [comment]
Bumping this up @Aricg - let me know...

**Comment by Aricg** [comment]
Hi @jmertic this is on my board, but I'm not sure how long it will be till I get to it. I'll update you when possible.

**Comment by jmertic** [comment]
ok - thanks!

**Comment by jmertic** [comment]
Any update on when you'd be ready to engage here?

**Comment by Aricg** [comment]
@jmertic  Since you guys already manage the Github org yourselves and don't have many committers, it's not seen as an important feature to implement at this time. I am swamped with other priorities I must sadly conclude that this will not get looked at in the near future.

**Comment by Frenchhorn005** [comment]
Will come back to this laterif needed.

Signed-of-by: Andre de Waal <andre.dewaal@ibm.com>

**Comment by Aricg** [comment]
@jmertic Hello, I have the code needed for self-serve committer promotions and project creations via github actions. Can we have a quick discussion at your leisure about this?

**Comment by jmertic** [comment]
Yes @Aricg - can we setup a call next week? Feel free to find an opening in my calendar.

**Pull request closed without merging**
